version: "3.9"
volumes:
    data:
    schemas:
    caddy_data:

networks:
    frontend:
    backend:

services:
    caddy:
        build:
            context: ./caddy
        volumes:
            - caddy_data:/data
        networks:
            - frontend
        ports:
            - "443:443"
            - "8448:8448"

    synapse:
        build:
            context: ./synapse
        restart: unless-stopped
        volumes:
            - data:/data
        depends_on:
            - postgres
        environment:
        networks:
            - backend
            - frontend
        environment:
            POSTGRES_USER: synapse
            POSTGRES_PASSWORD: passwort
            SYNAPSE_CONFIG_PATH: /config/homeserver.yaml
        logging:
            options:
                max-size: "100m"
                max-file: "3"

    postgres:
        image: postgres
        restart: unless-stopped
        environment:
            POSTGRES_PASSWORD: passwort
            POSTGRES_USER: synapse
            POSTGRES_INITDB_ARGS: --encoding=UTF-8 --lc-collate=C --lc-ctype=C
            POSTGRES_HOST: postgres
            POSTGRES_PORT: 5432
        volumes:
            - schemas:/var/lib/postgresql/data
        networks:
            - backend


